require 'util.matrixNorm'

randM=torch.rand(1000,2000):mul(5)
begin=os.clock()
acc_s1=matrixNorm:norm(randM,1,-1)
finish=os.clock()
print('take',finish-begin,'seconds')
print('acc_s1',acc_s1)
begin=os.clock()
app_s1=matrixNorm:norm(randM,1,500)
finish=os.clock()
print('take',finish-begin,'seconds')
print('app_s1',app_s1)
begin=os.clock()
acc_si=matrixNorm:norm(randM,1/0,-1)
finish=os.clock()
print('take',finish-begin,'seconds')
print('acc_si',acc_si)
begin=os.clock()
app_si=matrixNorm:norm(randM,1/0,500)
finish=os.clock()
print('take',finish-begin,'seconds')
print('app_si',app_si)